---

quorumFlags:
  privacy: false
  # this will erase keys - so be careful with this on validators
  removeKeysOnDelete: false
  isBootnode: true    # set this to true if this node is a bootnode
  usesBootnodes: true # set this to true if the network you are connecting to use a bootnode/s that are deployed in the cluster 

cluster:
  provider: azure  # choose from: local | aws | azure
  cloudNativeServices: true # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  reclaimPolicy: Delete # set to either Retain or Delete

aws:
  # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
  serviceAccountName: quorum-node-secrets-sa
  # the region you are deploying to
  region: ap-southeast-2

azure:
  # the script/bootstrap.sh uses the name 'quorum-pod-identity' so only change this if you altered the name
  identityName: quorum-pod-identity
  # the clientId of the user assigned managed identity created in the template
  identityClientId: efae6f7e-a346-4b2b-88e1-b81adb221320  
  keyvaultName: besu-dev-zaiodecs-vault
  # the tenant ID of the key vault
  tenantId: f9e879fc-5f3d-4ff3-8db7-262ef73edab4
  # the subscription ID to use - this needs to be set explictly when using multi tenancy
  subscriptionId: ccf62437-546d-4fdc-8f8e-8c1cbf1a4d2b


storage:
  sizeLimit: "20Gi"
  pvcSizeLimit: "20Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain 

# fixes permissions of volumes becuase besu runs as user `besu` and volumes prefer `root`
volumePermissionsFix:
  - local
  - aws

node:
  besu:
    envBesuOpts: ""
    resources:
      cpuLimit: 0.7
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    # privKey:
    # pubKey:
    dataPath: "/data/besu"
    keysPath: "/keys"
    privateKeyPath: "/keys/nodekey"
    genesisFilePath: "/etc/genesis/genesis.json"
    logging: INFO
    account:
      password: 'password'
      passwordPath: "/keys/accountPassword"    
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 30303
      discovery: true
      staticNodes: "/config/static/static-nodes.json"
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: false
    ws:
      enabled: true
      host: "0.0.0.0"
      port: 8546
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]'
      authenticationEnabled: false
    graphql:
      enabled: false
      host: "0.0.0.0"
      port: 8547
      corsOrigins: '["all"]'
    txPool:
      retentionHours: 999
      maxSize: 1024
    http:
      allowlist: '["*"]'
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 9545
      # enable if using prometheus-stack metrics monitoring
      serviceMonitorEnabled: false      
    metricsPush:
      enabled: false
      host: "5.5.5.5"
      port: 9091
      interval: 15
      prometheusJob: "besu"
    privacy:
      url: "http://localhost:9101"
      pubkeysPath: "/tessera"
      pubkeyFile: "tm.pub"
      onchainGroupsEnabled: false
    permissions:
      enabled: true
      filePath: ""
      nodes:
        enabled: false
        allowlist: ["enode://abcd..@1.2.3.3:30303","enode://efba..@1.2.3.4:besu-node-bootnode-1-0.besu-node-bootnode-1.besu.svc.cluster.local:30303"]
      accounts:
        enabled: false
        allowlist: ["0x0000000000000000000000000000000000008888"]
      nodesContract:
        enabled: false
        address: "0x0000000000000000000000000000000000009999"
      accountsContract:
        enabled: true
        address: "0x0000000000000000000000000000000000008888"  

  tessera:
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    tmkey: ""
    tmpub: ""
    password: "password"
    passwordPath: "/keys/tm.password"
    dataPath: "/data/tessera"
    keysPath: "/keys"
    port: 9000
    tpport: 9080
    q2tport: 9101

image:
  besu:
    repository: hyperledger/besu
    tag: 22.7.2
    pullPolicy: IfNotPresent
  tessera:
    repository: quorumengineering/tessera
    tag: 22.1.7
    pullPolicy: IfNotPresent
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: qgt-0.2.3
    pullPolicy: IfNotPresent

