image:
  explorer:
    repository: consensys/quorum-explorer
    tag: a642c14
    pullPolicy: IfNotPresent

containerPort: 25000
resources:
  requests:
    cpu: 1000m
    memory: 1G

explorerConfig: |
   {
   "algorithm": "qbft",
   "nodes": [{
       "name": "validator1",
       "client": "besu",
       "rpcUrl": "http://besu-node-validator-1-0.besu-node-validator-1.quorum.svc.cluster.local:8545",
       "privateTxUrl": ""
     },
     {
       "name": "validator2",
       "client": "besu",
       "rpcUrl": "http://besu-node-validator-2-0.besu-node-validator-2.quorum.svc.cluster.local:8545",
       "privateTxUrl": ""
     },
     {
       "name": "validator3",
       "client": "besu",
       "rpcUrl": "http://besu-node-validator-3-0.besu-node-validator-3.quorum.svc.cluster.local:8545",
       "privateTxUrl": ""
     },
     {
       "name": "validator4",
       "client": "besu",
       "rpcUrl": "http://besu-node-validator-4-0.besu-node-validator-4.quorum.svc.cluster.local:8545",
       "privateTxUrl": ""
     },
     {
       "name": "network-leader",
       "client": "besu",
       "rpcUrl": "http://besu-node-member-1-0.besu-node-network-leader.quorum.svc.cluster.local:8545",
       "privateTxUrl": "http://besu-node-network-leader.quorum.svc.cluster.local:9080",
       "privateKey": "0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
       "accountAddress": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
     },
     {
       "name": "manufacturer",
       "client": "besu",
       "rpcUrl": "http://besu-node-member-2-0.besu-node-manufacturer.quorum.svc.cluster.local:8545",
       "privateTxUrl": "http://besu-node-manufacturer.quorum.svc.cluster.local:9080",
       "privateKey": "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
       "accountAddress": "0x627306090abaB3A6e1400e9345bC60c78a8BEf57"
     },
     {
       "name": "upi-issuer",
       "client": "besu",
       "rpcUrl": "http://besu-node-member-2-0.besu-node-upi-issuer.quorum.svc.cluster.local:8545",
       "privateTxUrl": "http://besu-node-upi-issuer.quorum.svc.cluster.local:9080",
       "privateKey": "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
       "accountAddress": "0x627306090abaB3A6e1400e9345bC60c78a8BEf57"
     },
     {
       "name": "merchant",
       "client": "besu",
       "rpcUrl": "http://besu-node-member-2-0.besu-node-merchant.quorum.svc.cluster.local:8545",
       "privateTxUrl": "http://besu-node-merchant.quorum.svc.cluster.local:9080",
       "privateKey": "cc4e7c383eaefd6c6dd6491b591f8ee6cae7ae49aafa3622defe32b10e988251",
       "accountAddress": "0xf6085f4c90a6c80ac50f66448c4348f2121d58b4"
     },
     {
       "name": "acquirer",
       "client": "besu",
       "rpcUrl": "http://besu-node-member-2-0.besu-node-acquirer.quorum.svc.cluster.local:8545",
       "privateTxUrl": "http://besu-node-acquirer.quorum.svc.cluster.local:9080",
       "privateKey": "40de48835602c8e02c427cac1431cc413e7a0531d1de3b2aaedf982332ceb22e",
       "accountAddress": "0x5c061e80b86cf9a123592187d71bc2ce6913917f"
     }
   ]
   }